version: '3'
services:
  nginx:
      image: nginx:latest
      ports:
          - "8082:80"
      volumes:
          - ./gcp:/gcp
          - ./site.conf:/etc/nginx/conf.d/default.conf
      links:
        - php
  php:
      image: dev-php-php${PHP_VERSION}-grpc-${GRPC}-protobuf-${PROTOBUF}
      build:
        context: ./php
        args:
          GRPC: ${GRPC}
          PROTOBUF: ${PROTOBUF}
          PHP_VERSION: ${PHP_VERSION}
      volumes:
        - ./gcp:/gcp
      environment:
        - GOOGLE_APPLICATION_CREDENTIALS=/gcp/keys/${KEY}.json
